### ISSUE TITLE
compat entries unnecessarily restrictive

### ISSUE THREAD

**Issue by bclyons12** [rvignolo/RayTracing.jl#13]
I found incompatibilities between RayTracing and other packages I've been using, which come from the restrictive compat entries (presumably from CompatHelper) in RayTracing. I've tried just deleting the compat entries in RayTracing. Everything worked well and the regression tests pass. Could you please either delete the compat entries or update them appropriately? Thank you!

**Comment by rvignolo** [comment]
Hi again @bclyons12! 

I will do this later today and release a new version. Thanks for your testing and feedback!

**Comment by rvignolo** [comment]
solved!
